import chromaClient from "../config/chroma.js";

const collectionName =
  process.env.CHROMA_COLLECTION || "crm_documents";

let collection;

/*
 * Exported so the retrieval side (rag-retrieval.service.js) reads the
 * SAME collection handle the ingestion side writes to — one client,
 * one collection name, no second source of truth.
 */
export const getCollection = async () => {
  if (!collection) {
    // embeddingFunction: null is required. Without it the client tries to
    // instantiate DefaultEmbeddingFunction (a separate @chroma-core/default-embed
    // package) and throws. We always pass embeddings in explicitly, generated by
    // embedding.service.js, so Chroma never needs to embed anything itself.
    collection = await chromaClient.getOrCreateCollection({
      name: collectionName,
      embeddingFunction: null,
    });
  }

  return collection;
};

export const addDocumentChunks = async ({
  documentId,
  chunks,
  embeddings,
  metadata,
}) => {
  if (!chunks.length) {
    const error = new Error("No chunks provided");
    error.statusCode = 400;
    throw error;
  }

  if (chunks.length !== embeddings.length) {
    const error = new Error(
      "Chunks and embeddings count must match"
    );

    error.statusCode = 400;

    throw error;
  }

  const collection = await getCollection();

  const ids = chunks.map(
    (_, index) => `${documentId}-${index}`
  );

  const metadatas = chunks.map((_, index) => ({
    documentId: documentId.toString(),
    chunkIndex: index,
    ...metadata,
  }));

  await collection.add({
    ids,
    documents: chunks,
    embeddings,
    metadatas,
  });

  return {
    documentId,
    chunksStored: chunks.length,
  };
};

/*
 * Remove every chunk belonging to one document.
 *
 * Deleting a document from MongoDB and S3 is not enough on its own: the
 * vectors outlive it, so retrieval keeps matching them and the chat
 * answers — and cites — a file that no longer exists. This closes that
 * gap.
 *
 * Matched on the documentId metadata rather than reconstructing the
 * `${documentId}-${index}` ids, so it stays correct no matter how many
 * chunks were written.
 */
export const deleteDocumentChunks = async (documentId) => {
  if (!documentId) {
    const error = new Error("documentId is required");
    error.statusCode = 400;
    throw error;
  }

  const collection = await getCollection();

  await collection.delete({
    where: { documentId: documentId.toString() },
  });

  return { documentId };
};