import chromaClient from "../config/chroma.js";

const collectionName =
  process.env.CHROMA_COLLECTION || "crm_documents";

let collection;

const getCollection = async () => {
  if (!collection) {
    // embeddingFunction: null is required. Without it the client tries to
    // instantiate DefaultEmbeddingFunction (a separate @chroma-core/default-embed
    // package) and throws. We always pass embeddings in explicitly, generated by
    // embedding.service.js, so Chroma never needs to embed anything itself.
    collection = await chromaClient.getOrCreateCollection({
      name: collectionName,
      embeddingFunction: null,
    });
  }

  return collection;
};

export const addDocumentChunks = async ({
  documentId,
  chunks,
  embeddings,
  metadata,
}) => {
  if (!chunks.length) {
    const error = new Error("No chunks provided");
    error.statusCode = 400;
    throw error;
  }

  if (chunks.length !== embeddings.length) {
    const error = new Error(
      "Chunks and embeddings count must match"
    );

    error.statusCode = 400;

    throw error;
  }

  const collection = await getCollection();

  const ids = chunks.map(
    (_, index) => `${documentId}-${index}`
  );

  const metadatas = chunks.map((_, index) => ({
    documentId: documentId.toString(),
    chunkIndex: index,
    ...metadata,
  }));

  await collection.add({
    ids,
    documents: chunks,
    embeddings,
    metadatas,
  });

  return {
    documentId,
    chunksStored: chunks.length,
  };
};