import crypto from "node:crypto";

import credential from "../config/config.js";

/*
 * Identity for an ANONYMOUS chat visitor.
 *
 * A public visitor has no account, so something has to tie their chat
 * requests back to the lead they created. That something is this
 * cookie, and the rules around it are what keep one visitor from
 * reading another's lead:
 *
 *   - the value is generated by the SERVER from a CSPRNG, never
 *     supplied or chosen by the client;
 *   - it is httpOnly, so page JavaScript cannot read it and an XSS
 *     cannot exfiltrate it;
 *   - it is opaque — it encodes nothing, it is only ever looked up;
 *   - the server resolves the lead FROM it. The browser never sends a
 *     leadId, so there is no id for anyone to tamper with.
 *
 * It is not an authentication token and grants nothing beyond "keep
 * talking to the assistant about the enquiry this browser opened".
 */

const CHAT_SESSION_COOKIE = "chatSession";

/* Long enough to outlast a browsing session, short enough to expire. */
const CHAT_SESSION_MAX_AGE_MS = 7 * 24 * 60 * 60 * 1000;

const cookieOptions = {
  httpOnly: true,
  secure: credential.nodeEnv === "production",
  sameSite: "lax",
  path: "/",
};

/* 256 bits of randomness — not guessable, not enumerable. */
const createChatSessionId = () => crypto.randomBytes(32).toString("hex");

const setChatSessionCookie = (res, sessionId) => {
  res.cookie(CHAT_SESSION_COOKIE, sessionId, {
    ...cookieOptions,
    maxAge: CHAT_SESSION_MAX_AGE_MS,
  });
};

const clearChatSessionCookie = (res) => {
  res.clearCookie(CHAT_SESSION_COOKIE, cookieOptions);
};

/*
 * Read the cookie, but only accept a value with the exact shape the
 * server issues. Anything else is treated as absent rather than being
 * used as a database lookup key.
 */
const readChatSessionId = (req) => {
  const value = req.cookies?.[CHAT_SESSION_COOKIE];

  if (typeof value !== "string" || !/^[a-f0-9]{64}$/.test(value)) {
    return null;
  }

  return value;
};

export {
  CHAT_SESSION_COOKIE,
  CHAT_SESSION_MAX_AGE_MS,
  createChatSessionId,
  setChatSessionCookie,
  clearChatSessionCookie,
  readChatSessionId,
};
